name: Django CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: zergling
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: $
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
        DBENGINE: django.db.backends.mysql
        DBNAME: mysql
        DBUSER: root
        DBPASSWORD: zergling
        DBHOST: 127.0.0.1
        DBPORT: $
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DBENGINE: django.db.backends.mysql
        DBNAME: mysql
        DBUSER: root
        DBPASSWORD: zergling
        DBHOST: 127.0.0.1
        DBPORT: $